# Generated by Django 3.1.5 on 2021-05-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_db', '0003_auto_20210517_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
