# Generated by Django 3.1.5 on 2021-05-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_db', '0005_auto_20210517_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
