# Generated by Django 3.1.5 on 2021-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
