# Generated by Django 3.2.3 on 2021-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('studying_at_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
