# Generated by Django 3.2.3 on 2021-05-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carna_db', '0002_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
    ]
