# Generated by Django 3.2.3 on 2021-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carna_db', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Match_Example',
            },
        ),
    ]
